version: '3'

services:
  proxy:
    build: ../Bookable-proxy
    ports:
      - "3000:3000"
  gallery-service:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - 'database'
    restart: on-failure

  database:
    image: mongo:latest
    volumes:
      - ./data:/data/db