version: '3'

services:
  proxy:
    build: ../Bookable-Proxy
    container_name: 'proxy'
    ports:
      - "3000:3000"
  gallery-service:
    build: .
    container_name: 'gallery-service'
    ports:
      - '3001:3001'
    depends_on:
      - 'database'
    restart: on-failure

  database:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - ./data:/data/db